services:
  scraper:
    build: .
    volumes:
      - ./:/app
    container_name: pr-scraper
    entrypoint: []  # Override Dockerfile ENTRYPOINT
    command: tail -f /dev/null  # Keep container running
